### PR TITLE
Milestone 5

### PR DESCRIPTION
**Pull request by geraldgsh**
1. Implement the styling of the different components based on the design
2 Created an asset folder for all CSS files
3. Added a constant folder for categories array

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi Team :clap: 

### Awesome Design Guys!! :+1:  Welldone 😄 

Let's try to make just two updates so that we can meet up with the project requirements then you're done with this project;

**1.** kindly add text `book` and the dropdown `category` horizontally beside each other as it is in the below screenshot from the project given spec.
image
image


**2.** App responsiveness; the `book form` seems scattered on the mobile view.
image


**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by geraldgsh** [comment]
Thanks @bellom we'll make the required changes.

**Review by Oghenebrume50 — APPROVED** [review]
### STATUS: APPROVED 

Hi @geraldgsh @Aaron-RN  good job guys :+1:  this is lovely clean implementation of  the UI and kudos for the correction as directed by the previous reviewer :slightly_smiling_face:  Please merge and move on **This is approved**

**RAPHAEL NORIODE** :world_map:

**Comment by geraldgsh** [comment]
@Oghenebrume50 Thanks for the kind words

**Pull request merged**
